### ISSUE TITLE
Has this been tested?

### ISSUE THREAD

**Issue by sbelectronics** [TheLittleEngineers/CoCoDragon-MultiPakInterface-CC-Multi-Pak_Version_1.2#1]
Hi, the README says there will be an update once the boards have been fabbed and tested. I was wondering if the test was successful? Thanks.

**Comment by TheLittleEngineers** [comment]
Hello. The board was ordered and successfully tested by this amazing fellow here (is this you by chance?): https://www.smbaker.com/tandy-color-computer-resources
I am updating this archive to include a collection of alternative PAL chips that offer various improved functionality.
